# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeagueInfo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeagueInfo

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'KeychainAccess'
  target 'LeagueInfoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LeagueInfoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
